/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0jTkjQCt6Rt
 */
import Link from "next/link"
import { CardContent, Card } from "@/components/ui/card"
import { AvatarImage, Avatar } from "@/components/ui/avatar"

export default function v0() {
  return (
    <main className="flex flex-col min-h-screen">
      <header className="w-full h-16 flex items-center justify-between px-4 bg-white dark:bg-gray-800">
        <div className="font-semibold text-xl">Data Science and Informatics Club</div>
        <nav className="hidden md:flex gap-4">
          <Link className="hover:underline" href="#">
            Home
          </Link>
          <Link className="hover:underline" href="#">
            About Us
          </Link>
          <Link className="hover:underline" href="#">
            Events
          </Link>
          <Link className="hover:underline" href="#">
            Members
          </Link>
          <Link className="hover:underline" href="#">
            Projects
          </Link>
          <Link className="hover:underline" href="#">
            Resources
          </Link>
          <Link className="hover:underline" href="#">
            Contact
          </Link>
        </nav>
      </header>
      <section
        className="w-full h-screen bg-cover bg-center flex items-center justify-center text-center"
        id="home"
        style={{
          backgroundImage: "url('/malachowwsky.jpeg')",
        }}
      >
        <div className="text-white">
          <h1 className="text-4xl md:text-6xl font-bold mb-4">Welcome to the Data Science and Informatics Club</h1>
          <p className="text-xl md:text-2xl">
            We are a community of data enthusiasts committed to promoting knowledge sharing and collaboration in the
            field of data science and informatics.
          </p>
        </div>
      </section>
      <section className="w-full py-12 px-4 md:px-6 bg-gray-100 dark:bg-gray-800" id="about">
        <h2 className="text-3xl font-bold mb-4">About Us</h2>
        <p className="text-lg mb-4">
          The Data Science and Informatics Club was founded in 2020 with the aim of fostering a community of data
          enthusiasts. Our mission is to promote knowledge sharing and collaboration in the field of data science and
          informatics.
        </p>
        <p className="text-lg">
          By joining our club, you will have the opportunity to participate in workshops, webinars, and guest lectures,
          work on exciting projects, and access a curated list of resources to help you further your knowledge in data
          science and informatics.
        </p>
      </section>
      <section className="w-full py-12 px-4 md:px-6" id="events">
        <h2 className="text-3xl font-bold mb-4">Upcoming Events</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <Card>
            <CardContent>
              <h3 className="font-semibold">Workshop on Data Visualization</h3>
              <p className="text-sm text-gray-500">January 15, 2024, 10:00 AM</p>
              <p className="mt-2">Learn the basics of data visualization using popular libraries in Python.</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent>
              <h3 className="font-semibold">Webinar on Machine Learning</h3>
              <p className="text-sm text-gray-500">February 20, 2024, 2:00 PM</p>
              <p className="mt-2">
                Join us for a webinar on the fundamentals of machine learning and its applications.
              </p>
            </CardContent>
          </Card>
          <Card>
            <CardContent>
              <h3 className="font-semibold">Guest Lecture on Big Data</h3>
              <p className="text-sm text-gray-500">March 25, 2024, 6:00 PM</p>
              <p className="mt-2">Don't miss our guest lecture on big data and its impact on modern businesses.</p>
            </CardContent>
          </Card>
        </div>
      </section>
      <section className="w-full py-12 px-4 md:px-6 bg-gray-100 dark:bg-gray-800" id="members">
        <h2 className="text-3xl font-bold mb-4">Our Members</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="flex items-center gap-4">
            <Avatar className="h-12 w-12">
              <AvatarImage alt="Member Name" src="/placeholder-avatar.jpg" />
            </Avatar>
            <div>
              <div className="font-medium">Member Name</div>
              <div className="text-sm text-gray-500">Member Bio</div>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 px-4 md:px-6" id="projects">
        <h2 className="text-3xl font-bold mb-4">Our Projects</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <Card>
            <CardContent>
              <h3 className="font-semibold">Project Title</h3>
              <p className="mt-2">Short description of the project.</p>
            </CardContent>
          </Card>
        </div>
      </section>
      <section className="w-full py-12 px-4 md:px-6 bg-gray-100 dark:bg-gray-800" id="resources">
        <h2 className="text-3xl font-bold mb-4">Resources</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <div>
            <h3 className="font-semibold">Resource Title</h3>
            <p className="mt-2">Short description of the resource.</p>
          </div>
        </div>
      </section>
      <section className="w-full py-12 px-4 md:px-6" id="contact">
        <h2 className="text-3xl font-bold mb-4">Contact Us</h2>
        <p className="text-lg mb-4">Email: club@university.edu</p>
        <p className="text-lg">Follow us on social media: @dsiclub</p>
      </section>
      <footer className="w-full h-16 flex items-center justify-center px-4 bg-white dark:bg-gray-800">
        <div className="text-sm text-gray-500 dark:text-gray-400">© 2024 Data Science and Informatics Club</div>
      </footer>
    </main>
  )
}
