export const articles = [
  {
    id: 1,
    title: 'DSI wins student organization of the year',
    image: '/images/newsletter/grso-org-year25/1.jpeg',
    articleImage: '/images/newsletter/grso-org-year25/2.jpeg',
    date: 'March 2025',
    category: 'Awards',
    featured: true,
    description: `DSI was named Organization of the Year (GRSO) at this year's Student Involvement Awards across all UF student organizations! 🎉\n\nWe are honored and humbled to share this with all of you who have continuously supported us, whether by attending our workshops, competing alongside us at hackathons, or helping fund our initiatives.\n\nWe also want to congratulate our newly elected External Vice President, My Pham, on winning the Emerging Gator Award, which recognizes outstanding underclassmen leaders. We are so proud to have My on our team.\n\nThis award is a testament to the work we have been doing and the core belief that knowledge should be accessible to all.`,
  },
  {
    id: 2,
    title: "DSI member's chatbot SAMSARA wins AI hackathon",
    image: '/images/newsletter/samsara25/1.jpeg',
    articleImage: '/images/newsletter/samsara25/1.jpeg',
    date: 'February 2025',
    category: 'Competition',
    featured: false,
    description: `Join us in congratulating one of our students, Kalim Qazi, in winning first place nationally at Sentient's Hackathon!\n\n Across 7 days of public access, Samsara logged nearly 24 hours of total usage and received over 2,800 messages, all from organic traffic. We are extremely proud of you and of your hard work!`,
  },
  {
    id: 3,
    title: "DSI members win Best Visualization at DataFest 2025",
    image: '/images/newsletter/datafest25/1.jpg',
    articleImage: '/images/newsletter/datafest25/1.jpg',
    date: 'February 2025',
    category: 'Competition',
    featured: false,
    description: `Matheus Kunzler Maldaner, Ishan Kumthekar, Aadhitya Vijaisenthi, Aaron Goffstein and Adit Potta won Best Visualization at DataFest 2025!`,
  },
  {
    id: 4,
    title: "DSI members win Most Popular Award at 2024 AI Days Hackathon",
    image: '/images/newsletter/ai-days24/1.jpg',
    articleImage: '/images/newsletter/ai-days24/2.jpg',
    date: 'December 2024',
    category: 'Competition',
    featured: false,
    description: `Raul Valle, Landon Nayab, Matheus Kunzler Maldaner and Stephen Wormald won Most Popular Award for their FPGA Implementation of a Differentiable Logic Gate Neural Network.`,
  },
  {
    id: 5,
    title: "DSI members win Best AI Hack at SwampHacks 2025",
    image: '/images/newsletter/swamphacks25/1.jpg',
    articleImage: '/images/newsletter/swamphacks25/1.jpg',
    date: 'January 2025',
    category: 'Competition',
    featured: false,
    description: `DSI members Matheus Kunzler Maldaner, Kristian O'Connor, Danush Singla and Pranav Bhargava won the Best AI Hack at SwampHacks 2025, University of Florida's Largest Hackathon, by programming an interface to visualize the inner workings of Differentiable Logic Gate Neural Networks.`,
  },
  {
    id: 6,
    title: "DSI members win Most Popular Award at ShellHacks 2024",
    image: '/images/newsletter/shellhacks24/1.jpg',
    articleImage: '/images/newsletter/shellhacks24/2.jpg',
    date: 'September 2024',
    category: 'Competition',
    featured: false,
    description: `Thanks to the financial support of Dr. Juan Gilbert and CISE and AIIRI's collaboration, DSI was able to send 54 students to compete at ShellHacks 2024, Florida's largest hackathon with over 700 participants! DSI members Raul Valle, Matheus Kunzler Maldaner, Emily Jiji and Evan Partidas won the Most Popular project and several other UF students won specific company track prizes.`,
  },
  {
    id: 7,
    title: "DSI and UFIT hosted Nvidia Deep Learning Workshop",
    image: '/images/newsletter/nvidia-dli24/1.jpg',
    articleImage: '/images/newsletter/nvidia-dli24/2.jpg',
    date: 'November 2024',
    category: 'Workshop',
    featured: false,
    description: `DSI and UFIT hosted a Deep Learning Workshop at Nvidia's Auditorium in Malachowsky Hall. The workshop was led by Matt Gitzendanner and attended by 400 students. At the end of this four part series, students who successfully completed the course were able to earn an official Nvidia Deep Learning Certificate for free!`,
  },
  {
    id: 8,
    title: "DSI members win Best Overall at DataFest 2024",
    image: '/images/newsletter/datafest24/2.jpg',
    articleImage: '/images/newsletter/datafest24/1.jpg',
    date: 'April 2024',
    category: 'Competition',
    featured: false,
    description: `Eric Chao, Justin Witter, Patrick Leiman, Matheus Kunzler Maldaner and Raul Valle won Best Overall at DataFest 2024!`,
  },
  {
    id: 9,
    title: "DSI members win Best AI Hack and 2nd Place Overall at OSC Mini Hackathon",
    image: '/images/newsletter/osc-minihack24/1.png',
    articleImage: '/images/newsletter/osc-minihack24/1.png',
    date: 'March 2024',
    category: 'Competition',
    featured: false,
    description: `DSI members Matheus Kunzler Maldaner, Raul Valle and Sebastian Sosa won the Best AI Hack and 2nd Place Overall at OSC Mini Hackathon by programming a Discord Bot that can use sentiment analysis to predict when undesired content is posted in a server.`,
  },
  {
    id: 10,
    title: "DSI wins Career Influencer Award",
    image: '/images/newsletter/ccc-award25/1.jpg',
    articleImage: '/images/newsletter/ccc-award25/2.jpg',
    date: 'April 2025',
    category: 'Awards',
    featured: true,
    description: `We have recently been recognized by the UF Career Connections Center at this year's Career Influencer Awards 🎉\n\nWe extend our gratitude to the university departments that have enabled us to succeed over the past year.\nPictured are our President, Matheus Kunzler Maldaner, alongside our Internal Vice President, Ishan Kumthekar. We thank Matt Gitzendanner and Marquise M. McGriff, M.A., CCSP, also pictured, for their continuous support.\n\nWe are excited for what our new executive team will accomplish together and remain grounded in our belief that knowledge should be accessible to all. Thank you!`,
  },
]; 